// This file is generated by Slice Machine. Update with care!

import Header from './Header';
import Project from './Project';
import TestHome from './TestHome';

export {
	Header,
	Project,
	TestHome,
};

export const components = {
	header: Header,
	project: Project,
	test_home: TestHome,
};
