// This file is generated by Slice Machine. Update with care!

import Project from './Project';
import TestHome from './TestHome';

export {
	Project,
	TestHome,
};

export const components = {
	project: Project,
	test_home: TestHome,
};
